SELECT a.ASSINGN_NUM, e.EMP_NUM, p.PROJ_NUM, a.ASSIGN_CHARGE,
(a.ASSIGN_CHG_HR * a.ASSIGN_HOURS) AS CALCULATED_CHARGE
FROM ASSIGNMENT a
JOIN EMPLOYEE e
ON a.EMP_NUM = e.EMP_NUM
JOIN PROJECT P
ON a.PROJ_NUM = p.PROJ_NUM
ORDER BY
a.ASSIGN_NUM;
