SELECT p.PROJ_NAME, p.PROJ_VALUE, p.PROJ_BALANCE,
e.EMP_LNAME, e.EMP_FNAME, e.EMP_FNAME, e.EMP_INITIAL, 
j.JOB_CODE, j.JOB_DESCRIPTION, j.JOB_CHG_HOUR
FROM EMPLOYEE e
JOIN PROJECT p
ON e.EMP_NUM = p.EMP_NUM
JOIN JOB j
ON e.JOB_CODE = j.JOB_CODE
ORDER BY e.EMP_LNAME;
