SELECT
	I.INV_NUMBER,
    CAST(SUM(L.LINE_UNITS * L.LINE_PRICE) AS DECIMAL(10,2)) AS `Invoice Total`
FROM
	INVOICE I
    JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY
	I.INV_NUMBER
ORDER BY
	I.INV_NUMBER;