SELECT
	C.CUS_CODE,
	I.INV_NUMBER,
    ROUND(SUM(L.LINE_UNITS * L.LINE_PRICE),2) AS `Invoice Total`
FROM
	CUSTOMER C
	JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
    JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY
	I.INV_NUMBER
ORDER BY
	C.CUS_CODE,
	I.INV_NUMBER;