SELECT
	C.CUS_CODE,
    C.CUS_BALANCE,
    ROUND(SUM(L.LINE_UNITS * L.LINE_PRICE ),2)  AS `Total Purchases`,
	COUNT(C.CUS_CODE) AS `Number of Purcharses`, 
    ROUND(AVG(L.LINE_UNITS * L.LINE_PRICE),2) AS `Average Purchase Amount`  
FROM
	CUSTOMER C
    JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
    JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
GROUP BY
	C.CUS_CODE
ORDER BY
	C.CUS_CODE;