SELECT
	COUNT(DISTINCT I.INV_NUMBER) AS `Total Invoices`,
    ROUND(SUM(L.LINE_UNITS * L.LINE_PRICE) ,2) AS `Total Sales`,
    ROUND(MIN(CUSTOMER_TOTAL.TOTAL_PURCHASE),2) AS `Minimum Customer Purchases`,
    ROUND(MAX(CUSTOMER_TOTAL.TOTAL_PURCHASE),2) AS `Largest Customer Purchases`,
    ROUND(SUM(L.LINE_UNITS * L.LINE_PRICE) / COUNT(DISTINCT I.CUS_CODE),2) AS `Average Customer Purchases`
FROM
	INVOICE I
    JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
    JOIN (
			SELECT
				C.CUS_CODE,
                SUM(L.LINE_UNITS * L.LINE_PRICE) AS TOTAL_PURCHASE
			FROM
				CUSTOMER C
                JOIN INVOICE I ON C.CUS_CODE = I.CUS_CODE
                JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
			GROUP BY C.CUS_CODE
	) AS CUSTOMER_TOTAL ON CUSTOMER_TOTAL.CUS_CODE = I.CUS_CODE;