CREATE TABLE EMP_1 (
	EMP_NUM VARCHAR(3) PRIMARY KEY,
    EMP_LNAME VARCHAR(15), 
    EMP_FNAME VARCHAR(15),
	EMP_INITIAL CHAR(1),
    EMP_HIREDATE DATE,
    JOB_CODE VARCHAR(3),
	CONSTRAINT FK_JOB_CODE FOREIGN KEY (JOB_CODE) REFERENCES JOB (JOB_CODE)
);
